name: lxd-indicator
base: core22
version: '0.1'
summary: LXD instance status indicator
description: |
  A simple system tray indicator for displaying the status of LXD instances
  and performing basic actions.
grade: stable # Or devel, if preferred for initial releases
confinement: strict

apps:
  lxd-indicator:
    command: bin/desktop-launch.sh
    plugs:
      - network
      - gsettings
      - lxd
      - desktop
      - opengl
      - wayland
      - x11
      - gtk-common-themes
      - icon-themes
      - sound-themes
    autostart: lxd-indicator.desktop
    environment:
      GTK_USE_PORTAL: '1'

parts:
  lxd-indicator:
    plugin: python
    source: .
    python-packages:
      - pylxd
    stage-packages:
      - python3-gi
      - gir1.2-gtk-3.0
      - gir1.2-ayatanaappindicator3-0.1
      - libayatana-appindicator3-1
      - libgirepository-1.0-1
      - gir1.2-gdkpixbuf-2.0
      - dconf-gsettings-backend
      - libgtk-3-bin
      - adwaita-icon-theme-full
      - gnome-themes-extra
      - shared-mime-info
    override-build: |
      snapcraftctl build
      install -D -m 755 $SNAPCRAFT_PART_SRC/snap/command-chain/desktop-launch.sh $SNAPCRAFT_PART_INSTALL/bin/desktop-launch.sh
      install -D -m 755 $SNAPCRAFT_PART_SRC/lxd-indicator.py $SNAPCRAFT_PART_INSTALL/bin/lxd-indicator.py
      install -D -m 644 $SNAPCRAFT_PART_SRC/lxd_logo.png $SNAPCRAFT_PART_INSTALL/lxd_logo.png
      install -D -m 644 $SNAPCRAFT_PART_SRC/lxd-indicator.desktop $SNAPCRAFT_PART_INSTALL/usr/share/applications/lxd-indicator.desktop
