name: lxd-indicator
base: core22
version: '0.1'
summary: LXD instance status indicator
description: |
  A simple system tray indicator for displaying the status of LXD instances
  and performing basic actions.
grade: stable # Or devel, if preferred for initial releases
confinement: strict

apps:
  lxd-indicator:
    command: bin/lxd-indicator.py
    command-chain: [snap/command-chain/desktop-launch]
    extensions:
      - gnome # Use 'gnome' for core22, not 'gnome-3-38'
    plugs:
      - network
      - gsettings
      - lxd
      - desktop
      - opengl
      - wayland
      - x11
    autostart: lxd-indicator.desktop
    environment:
      GTK_USE_PORTAL: '1'

parts:
  lxd-indicator:
    plugin: python
    source: . # This will copy lxd-indicator.py and lxd_logo.png
    python-packages:
      - pylxd
    stage-packages:
      - python3-gi
      - gir1.2-gtk-3.0
      - gir1.2-appindicator3-0.1
      - libappindicator3-1
      - libgirepository-1.0-1
      - gir1.2-gdkpixbuf-2.0
    organize:
      lxd-indicator.py: bin/lxd-indicator.py
      lxd_logo.png: lxd_logo.png
      lxd-indicator.desktop: usr/share/applications/lxd-indicator.desktop
