name: Snap CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-snap:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        sudo snap install --classic snapcraft
        sudo snap install --classic lxd

    - name: Configure LXD
      run: |
        sudo lxd init --auto
        sudo usermod -a -G lxd $USER

    - name: Debug LXD Network
      run: |
        set -ex
        echo "--- Host IP Information ---"
        ip a
        echo "--- LXD Network List ---"
        sudo lxc network list
        echo "--- LXD Bridge Configuration ---"
        sudo lxc network show lxdbr0 || echo "lxdbr0 not found or command failed"
        echo "--- Launching Test Container ---"
        sudo lxc launch images:ubuntu/22.04 test-container
        sleep 15
        echo "--- LXD Container List ---"
        sudo lxc list
        echo "--- Checking Container Connectivity ---"
        sudo lxc exec test-container -- ping -c 3 8.8.8.8
        echo "--- Checking Container DNS and Package Manager ---"
        sudo lxc exec test-container -- cat /etc/resolv.conf
        sudo lxc exec test-container -- apt-get update
        echo "--- LXD Test Container Logs ---"
        sudo lxc info test-container --show-log
        echo "--- Cleaning up test container ---"
        sudo lxc delete --force test-container

    - name: Build the snap
      # Run build with the lxd group's permissions.
      run: sg lxd -c "snapcraft"

    - name: Install the snap
      run: |
        sudo snap install --dangerous lxd-indicator_*.snap
        sudo snap connect lxd-indicator:lxd

    - name: Test the snap
      run: |
        set -ex
        # Run test with the lxd group's permissions.
        sg lxd -c "
        set -ex
        xvfb-run lxd-indicator > app.log 2>&1 &
        sleep 10
        echo '--- Application logs ---'
        cat app.log
        echo '------------------------'
        grep 'Successfully connected to LXD' app.log
        pkill -f lxd-indicator.py
        "
