name: Snap CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-snap:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        sudo snap install --classic snapcraft
        sudo snap install --classic lxd

    - name: Wait for snapd
      run: sudo snap wait system seed.loaded

    - name: Configure LXD
      run: |
        sudo lxd init --auto
        sudo usermod -a -G lxd $USER

    - name: Pre-install build dependencies
      run: |
        sudo snap install gtk-common-themes
        sudo snap install gnome-42-2204-sdk

    - name: Build the snap
      # Build in destructive mode and print logs on failure.
      run: |
        snapcraft --destructive-mode || (cat /home/runner/.local/state/snapcraft/log/snapcraft-*.log && exit 1)

    - name: Install the snap
      run: |
        sudo snap install --dangerous lxd-indicator_*.snap
        sudo snap connect lxd-indicator:lxd

    - name: Test the snap
      run: |
        set -ex
        # Run test with the lxd group's permissions.
        sg lxd -c "
        set -ex
        xvfb-run lxd-indicator > app.log 2>&1 &
        sleep 10
        echo '--- Application logs ---'
        cat app.log
        echo '------------------------'
        grep 'Successfully connected to LXD' app.log
        pkill -f lxd-indicator.py
        "
