name: Snap CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-snap:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        sudo snap install --classic snapcraft
        sudo snap install --classic lxd

    - name: Wait for snapd
      run: sudo snap wait system seed.loaded

    - name: Configure LXD and restart snapd
      run: |
        sudo lxd init --auto
        sudo usermod -a -G lxd $USER
        sudo systemctl restart snapd

    - name: Pre-install build dependencies with retries
      run: |
        for snap in gtk-common-themes gnome-42-2204-sdk gnome-42-2204; do
          echo "--- Installing $snap ---"
          for i in 1 2 3; do
            if sudo snap install "$snap"; then
              echo "$snap installed successfully."
              break
            fi
            if [ $i -eq 3 ]; then
              echo "Failed to install $snap after 3 attempts."
              exit 1
            fi
            echo "Failed to install $snap, retrying in 10 seconds..."
            sleep 10
          done
        done

    - name: Build the snap
      # Build in destructive mode and print logs on failure.
      run: |
        snapcraft --destructive-mode || (cat /home/runner/.local/state/snapcraft/log/snapcraft-*.log && exit 1)

    - name: Install the snap
      run: |
        sudo snap install --dangerous lxd-indicator_*.snap
        sleep 10 # Give snapd time to process the new snap's interfaces
        sudo snap connect lxd-indicator:lxd lxd

    - name: Test the snap
      run: |
        set -ex
        # Run test with the lxd group's permissions.
        sg lxd -c "
        set -ex
        export GDK_BACKEND=x11
        mkdir -p /home/runner/snap/lxd-indicator/common/.cache
        xvfb-run lxd-indicator > app.log 2>&1 &
        sleep 10
        echo '--- Application logs ---'
        cat app.log
        echo '------------------------'
        grep 'Successfully connected to LXD' app.log
        pkill -f lxd-indicator.py
        "
